[package]
name = "svm-runtime-c-api"
version = "0.0.0"
authors = ["Yaron Wittenstein <yaron.wittenstein@gmail.com>"]
license = "MIT"
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies.wasmer]
git = "https://github.com/wasmerio/wasmer"
default-features = false
features = ["default-cranelift", "default-jit"]

[dependencies.wasmer-c-api]
git = "https://github.com/wasmerio/wasmer"
default-features = false
features = ["cranelift", "jit"]

[dependencies]
log = "0.4"
byteorder = "1.3.2"
svm-runtime = { path = "../svm-runtime", default-features = false }
svm-common = { path = "../svm-common" }
svm-kv = { path = "../svm-kv" }
svm-types = { path = "../svm-types" }
svm-codec = { path = "../svm-codec" }
svm-gas = { path = "../svm-gas" }
svm-layout = { path = "../svm-layout" }
svm-storage = { path = "../svm-storage" }
svm-compiler = { path = "../svm-compiler", default-features = false, features = [] }

[dev-dependencies]
wabt = "0.7.4"
serde_json = "1.0"
svm-sdk = { path = "../svm-sdk" }
svm-abi-encoder = { path = "../svm-abi/encoder" }

[build-dependencies]
cbindgen = "0.9.1"
