[package]
name = "svm-runtime-c-api"
version = "0.0.0"
authors = ["Yaron Wittenstein <yaron.wittenstein@gmail.com>"]
license = "MIT"
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies.wasmer-runtime]
default-features = false
git = "https://github.com/spacemeshos/wasmer"
branch = "develop"
features = ["default-backend-singlepass"]

[dependencies.wasmer-runtime-core]
default-features = false
git = "https://github.com/spacemeshos/wasmer"
branch = "develop"
features = ["backend-singlepass"]

[dependencies.wasmer-runtime-c-api]
default-features = false
git = "https://github.com/spacemeshos/wasmer"
branch = "develop"
features = ["singlepass-backend"]

[dependencies.wasmer-singlepass-backend]
git = "https://github.com/spacemeshos/wasmer"
branch = "develop"

[dependencies.svm-runtime]
default-features = false
path = "../svm-runtime"

[dependencies.svm-common]
path = "../svm-common"

[dependencies.svm-contract]
path = "../svm-contract"

[dependencies.svm-storage]
default-features = false
path = "../svm-storage"
features = ["svm_memory"]

[dependencies.svm-compiler]
default-features = false
path = "../svm-compiler"
features = []

[dependencies]
libc = "0.2"
byteorder = "1.3.2"

[dev-dependencies]
wabt = "0.7.4"
