[package]
name = "svm-compiler"
version = "0.0.0"
authors = ["Yaron Wittenstein <yaron.wittenstein@gmail.com>"]
license = "MIT"
edition = "2018"
readme = "README.md"
repository = "https://github.com/spacemeshos/svm"
homepage = "https://github.com/spacemeshos/svm"
description = "Spacemesh Virtual Machine"
publish = false

[dependencies.svm-common]
path = "../svm-common"
version = "0.0.0"

[dependencies.wasmer-compiler]
version="1.0.0-beta1"

[dependencies.wasmparser]
version = "0.65"
default-features = false

[dev-dependencies]
wat = "1.0"

[target.'cfg(unix)'.dependencies.wasmer]
version="1.0.0-beta1"
default-features = false
features = ["singlepass", "default-jit"]

[target.'cfg(windows)'.dependencies.wasmer]
version="1.0.0-beta1"
default-features = false
features = ["default-cranelift", "default-jit"]
