[package]
name = "svm-sdk"
version = "0.0.0"
authors = ["Yaron Wittenstein <yaron.wittenstein@gmail.com>"]
license = "MIT"
edition = "2018"
readme = "README.md"
repository = "https://github.com/spacemeshos/svm"
homepage = "https://github.com/spacemeshos/svm"
description = "Spacemesh Virtual Machine"
publish = false

[dependencies]
lazy_static = "1.4.0"
svm-sdk-alloc = { path = "alloc" }
svm-sdk-types = { path = "types" }
svm-sdk-host = { path = "host" }
svm-sdk-storage = { path = "storage" }
svm-abi-encoder = { path = "../svm-abi/encoder" }
svm-abi-decoder = { path = "../svm-abi/decoder" }
svm-sdk-macros = { path = "macros" }

[[test]]
name = "tests"
path = "tests/storage.rs"

[dev-dependencies]
trybuild = { version = "1.0", features = ["diff"] }