[package]
name = "svm-sdk-macros"
version = "0.1.0"
authors = ["Yaron Wittenstein <yaron.wittenstein@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
svm-sdk = { path = ".." }
svm-abi-encoder = { path = "../../svm-abi/encoder" }
svm-abi-decoder = { path = "../../svm-abi/decoder" }
proc-macro2 = "1.0.24"
quote = "1.0.7"
syn = "1.0.42"
cfg-if = "1.0.0"
