[package]
name = "svm-sdk-macros"
version = "0.1.0"
authors = ["Yaron Wittenstein <yaron.wittenstein@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
svm-sdk = { path = "../svm-sdk" }
proc-macro2 = "1.0.24"
quote = "1.0.7"
syn = "1.0.42"

[dev-dependencies]
trybuild = { version = "1.0", features = ["diff"] }