[package]
name = "svm-storage"
version = "0.0.0"
authors = ["Yaron Wittenstein <yaron.wittenstein@gmail.com>"]
license = "MIT"
edition = "2018"
readme = "README.md"
repository = "https://github.com/spacemeshos/svm"
homepage = "https://github.com/spacemeshos/svm"
description = "Spacemesh Virtual Machine"
publish = false

[dependencies.svm-kv]
path = "../svm-kv"
default-features = false

[dependencies.svm-common]
path = "../svm-common"

[dependencies.svm-hash]
path = "../svm-hash"

[dependencies.svm-types]
path = "../svm-types"

[dependencies.svm-layout]
path = "../svm-layout"

[dependencies]
lazy_static = "1.4.0"

[features]
default = ["default-memory"]
default-memory = ["svm-kv/default-memory"]
default-rocksdb = ["svm-kv/default-rocksdb"]