[package]
name = "svm-runtime"
version = "0.0.0"
authors = ["Yaron Wittenstein <yaron.wittenstein@gmail.com>"]
license = "MIT"
edition = "2018"
publish = false

[dependencies.svm-common]
path = "../svm-common"

[dependencies.svm-kv]
path = "../svm-kv"

[dependencies.svm-storage]
default-features = false
path = "../svm-storage"
features = ["default"]

[dependencies.svm-contract]
path = "../svm-contract"

[dependencies.svm-compiler]
path = "../svm-compiler"

[dependencies.wasmer-runtime]
default-features = false
git = "https://github.com/spacemeshos/wasmer"
branch = "develop"
features = ["default-backend-singlepass"]

[dependencies.wasmer-runtime-core]
default-features = false
git = "https://github.com/spacemeshos/wasmer"
branch = "develop"
features = ["backend-singlepass"]

[dependencies]
libc = "0.2"
log = "0.4"
byteorder = "1.3.2"
lazy_static = "1.4.0"

[dev-dependencies]
wabt = "0.7.4"
