[package]
name = "svm-runtime"
version = "0.0.0"
authors = ["Yaron Wittenstein <yaron.wittenstein@gmail.com>"]
license = "MIT"
edition = "2018"
publish = false

[dependencies.wasmer]
version="1.0.0-alpha5"
default-features = false
features = ["default-cranelift", "default-jit"]

[dependencies.wasmer-c-api]
version="1.0.0-alpha5"
default-features = false
features = ["cranelift", "jit"]

[dependencies.wasmer-vm]
version="1.0.0-alpha5"

[dependencies]
svm-common = { path = "../svm-common" }
svm-types = { path = "../svm-types" }
svm-kv = { path = "../svm-kv" }
svm-layout = { path = "../svm-layout" }
svm-storage = { path = "../svm-storage" }
svm-nibble = { path = "../svm-nibble" }
svm-codec = { path = "../svm-codec" }
svm-compiler = { path = "../svm-compiler" }
svm-gas = { path = "../svm-gas" }
log = "0.4"
byteorder = "1.3.2"
lazy_static = "1.4.0"
wat = "1.0"

[dev-dependencies]
maplit = "1.0.2"
svm-sdk = { path = "../svm-sdk" }
svm-abi-encoder = { path = "../svm-abi/encoder" }
svm-abi-decoder = { path = "../svm-abi/decoder" }