[package]
name = "svm-runtime"
version = "0.0.0"
authors = ["Yaron Wittenstein <yaron.wittenstein@gmail.com>"]
license = "MIT"
edition = "2018"
publish = false

[dependencies.wasmer]
version="1.0.0-beta1"
default-features = false

[dependencies]
log = "0.4"
byteorder = "1.3.2"
lazy_static = "1.4.0"
wat = "1.0"
svm-ffi = { path = "../svm-ffi" }
svm-common = { path = "../svm-common" }
svm-types = { path = "../svm-types" }
svm-kv = { path = "../svm-kv", default-features = false }
svm-layout = { path = "../svm-layout" }
svm-storage = { path = "../svm-storage" }
svm-nibble = { path = "../svm-nibble" }
svm-codec = { path = "../svm-codec" }
svm-compiler = { path = "../svm-compiler" }
svm-gas = { path = "../svm-gas" }

[dev-dependencies]
maplit = "1.0.2"
svm-sdk = { path = "../svm-sdk" }
svm-abi-encoder = { path = "../svm-abi/encoder" }
svm-abi-decoder = { path = "../svm-abi/decoder" }

[features]
default = ["default-memory"]
default-memory = ["svm-kv/default-memory"]
default-rocksdb = ["svm-kv/default-rocksdb"]