[package]
name = "svm-sdk-host"
version = "0.0.0"
authors = ["Yaron Wittenstein <yaron.wittenstein@gmail.com>"]
license = "MIT"
edition = "2018"
readme = "README.md"
repository = "https://github.com/spacemeshos/svm"
homepage = "https://github.com/spacemeshos/svm"
description = "Spacemesh Virtual Machine"
publish = false

[dependencies]
svm-sdk-alloc = { path = "../alloc" }
svm-sdk-types = { path = "../types" }
svm-sdk-std = { path = "../std" }
svm-abi-encoder = { path = "../../abi/encoder" }
svm-abi-decoder = { path = "../../abi/decoder" }

[dev-dependencies]
lazy_static = "1.4.0"

[features]
default = ["ffi", "mock"]
ffi = []
mock = []